import { readFileSync } from 'node:fs';
import type { CanonicalPr } from '../../src/canonical.js';
import type { PrTelemetryKey, TelemetryInput } from '../../src/types.js';
import { deriveAll } from '../../src/metrics.js';

let cached: CanonicalPr[] | null = null;
let cachedTelemetry: TelemetryInput | null = null;

/**
 * 203 real PRs, captured 2026-08-21 and already post-backfill.
 *
 * DERIVED, not verbatim: the raw GitHub capture lives beside the adapter that describes it, at
 * server/src/github/fixtures/sample-payload.json, and this file is generated from it by
 * `npm run fixture:canonical`. `core` cannot import from `server`, and it should not know
 * GitHub's response shape anyway. Regenerate after any change to `toCanonical()` — the seam
 * between raw and canonical is guarded by server/test/github.map.test.ts.
 */
export function samplePayload(): CanonicalPr[] {
    if (!cached) {
        const raw = readFileSync(new URL('./sample-canonical.json', import.meta.url), 'utf8');
        cached = JSON.parse(raw) as CanonicalPr[];
    }
    return cached;
}

/**
 * SYNTHETIC, unlike sample-payload.json. Generated by generate-telemetry.mjs against real
 * branch names from the payload above — see that file for the cases it encodes.
 */
export function sampleTelemetry(): TelemetryInput {
    if (!cachedTelemetry) {
        const raw = readFileSync(new URL('./telemetry-sessions.json', import.meta.url), 'utf8');
        cachedTelemetry = JSON.parse(raw) as TelemetryInput;
    }
    return cachedTelemetry;
}

/** The projection the server passes to attribute(). Built here so both tests agree on it. */
export function joinKeys(): PrTelemetryKey[] {
    return deriveAll(samplePayload()).map((pr) => ({
        repo: pr.repo,
        number: pr.number,
        author: pr.author,
        headRefName: pr.headRefName,
        createdAt: pr.createdAt,
        mergedAt: pr.mergedAt,
        size: pr.size,
        cycleHours: pr.cycleHours,
        commitsAfterHumanReview: pr.commitsAfterHumanReview,
    }));
}

export const FIXTURE_REPO = 'Leeloo-AI-RGA-OS/leeloo.ai';

/** The window the fixture was captured in, so `partial` week flags stay stable. */
export const FIXTURE_NOW = new Date('2026-08-21T12:00:00.000Z');
