import { readFileSync } from 'node:fs';
import type { PrTelemetryKey, RawPullRequest, TelemetryInput } from '../../src/types.js';
import { deriveAll } from '../../src/metrics.js';

let cached: RawPullRequest[] | null = null;
let cachedTelemetry: TelemetryInput | null = null;

/** Real API response covering 203 PRs, captured 2026-08-21. Already post-backfill. */
export function samplePayload(): RawPullRequest[] {
    if (!cached) {
        const raw = readFileSync(new URL('./sample-payload.json', import.meta.url), 'utf8');
        // The committed JSON carries no repo identity, because a GraphQL response does not: the
        // repo is knowledge the caller has. Stamped here rather than written into 203 records so
        // the payload stays a verbatim capture.
        cached = (JSON.parse(raw) as RawPullRequest[]).map((pr) => ({ ...pr, repo: FIXTURE_REPO }));
    }
    return cached;
}

/**
 * SYNTHETIC, unlike sample-payload.json. Generated by generate-telemetry.mjs against real
 * branch names from the payload above — see that file for the cases it encodes.
 */
export function sampleTelemetry(): TelemetryInput {
    if (!cachedTelemetry) {
        const raw = readFileSync(new URL('./telemetry-sessions.json', import.meta.url), 'utf8');
        cachedTelemetry = JSON.parse(raw) as TelemetryInput;
    }
    return cachedTelemetry;
}

/** The projection the server passes to attribute(). Built here so both tests agree on it. */
export function joinKeys(): PrTelemetryKey[] {
    return deriveAll(samplePayload()).map((pr) => ({
        repo: pr.repo,
        number: pr.number,
        author: pr.author,
        headRefName: pr.headRefName,
        createdAt: pr.createdAt,
        mergedAt: pr.mergedAt,
        size: pr.size,
        cycleHours: pr.cycleHours,
        commitsAfterHumanReview: pr.commitsAfterHumanReview,
    }));
}

export const FIXTURE_REPO = 'Leeloo-AI-RGA-OS/leeloo.ai';

/** The window the fixture was captured in, so `partial` week flags stay stable. */
export const FIXTURE_NOW = new Date('2026-08-21T12:00:00.000Z');
